development:
  adapter: oracle_enhanced
  database: "(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=192.168.1.222)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=ORCL)))"
  username: direct_debit
  password: direct_debit
production:
  adapter: oracle_enhanced
  database: "(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=192.168.1.222)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=ORCL)))"
  username: direct_debit
  password: direct_debit